FROM python:3.12

RUN pip install --no-cache-dir \
    transformers[torch]==4.54.1 \
    opencv-python==4.12.0.88 \
    requests==2.32.4 \
    flask==3.1.1 \
    redistimeseries==1.4.5 \
    python-dotenv==1.1.1 \
    pyJoules==0.5.1