FROM pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime

RUN pip install --no-cache-dir \
    transformers==4.54.1 \
    opencv-python==4.12.0.88 \
    requests==2.31.0 \
    flask==3.1.1 \
    redistimeseries==1.4.5 \
    python-dotenv==1.1.1 \
    pynvml==12.0.0 \
    pyJoules==0.5.1