FROM pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime

RUN pip install transformers

# Install opencv, requests and flask
RUN pip install opencv-python requests flask redistimeseries python-dotenv pynvml pyJoules