"""
Author: Aimilios Leftheriotis
Affiliations: Microlab@NTUA, VLSILab@UPatras

This module defines the MyServer class, which inherits from the {Pair}Server class defined in the {pair}_server module, depending on the target AI-framework/platform pair.

Methods:
- __init__(self, logger): Initializes the MyServer instance, sets up the logger, and logs all server values 
  by calling the log_all_server_values method from the WorkflowServer class.

DO NOT edit this file directly.
"""


# Custom module
import gpu_llm_trf_server

class MyServer(gpu_llm_trf_server.GpuLlmTrfServer):
    def __init__(self, logger):
        super().__init__(logger)
        self.log_all_server_values()