FROM nvcr.io/nvidia/pytorch:24.08-py3-igpu

RUN pip install --no-cache-dir \
    numpy==1.24.4 \
    transformers==4.55.2 \
    opencv-python==4.11.0.86 \
    requests==2.32.3 \
    flask==3.1.1 \
    redistimeseries==1.4.5 \
    python-dotenv==1.1.1
